Loading training set...
/opt/miniconda3/envs/deeplearning/lib/python3.10/site-packages/torch/utils/data/sampler.py:64: UserWarning: `data_source` argument is not used and will be removed in 2.2.0.You may still have custom implementation that utilizes it.
  warnings.warn("`data_source` argument is not used and will be removed in 2.2.0."

Num images:  809
Image shape: [3, 128, 128]
Label shape: [0]

Constructing networks...
Traceback (most recent call last):
  File "/Users/hongyiwang/Desktop/Projects/poke-fantasia/pokemon-generator/stylegan2/train.py", line 538, in <module>
    main() # pylint: disable=no-value-for-parameter
  File "/opt/miniconda3/envs/deeplearning/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/opt/miniconda3/envs/deeplearning/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/opt/miniconda3/envs/deeplearning/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/miniconda3/envs/deeplearning/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/opt/miniconda3/envs/deeplearning/lib/python3.10/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/hongyiwang/Desktop/Projects/poke-fantasia/pokemon-generator/stylegan2/train.py", line 531, in main
    subprocess_fn(rank=0, args=args, temp_dir=temp_dir)
  File "/Users/hongyiwang/Desktop/Projects/poke-fantasia/pokemon-generator/stylegan2/train.py", line 383, in subprocess_fn
    training_loop.training_loop(rank=rank, **args)
  File "/Users/hongyiwang/Desktop/Projects/poke-fantasia/pokemon-generator/stylegan2/training/training_loop.py", line 150, in training_loop
    G = dnnlib.util.construct_class_by_name(**G_kwargs, **common_kwargs).train().requires_grad_(False).to(device) # subclass of torch.nn.Module
  File "/opt/miniconda3/envs/deeplearning/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1152, in to
    return self._apply(convert)
  File "/opt/miniconda3/envs/deeplearning/lib/python3.10/site-packages/torch/nn/modules/module.py", line 802, in _apply
    module._apply(fn)
  File "/opt/miniconda3/envs/deeplearning/lib/python3.10/site-packages/torch/nn/modules/module.py", line 802, in _apply
    module._apply(fn)
  File "/opt/miniconda3/envs/deeplearning/lib/python3.10/site-packages/torch/nn/modules/module.py", line 802, in _apply
    module._apply(fn)
  [Previous line repeated 1 more time]
  File "/opt/miniconda3/envs/deeplearning/lib/python3.10/site-packages/torch/nn/modules/module.py", line 825, in _apply
    param_applied = fn(param)
  File "/opt/miniconda3/envs/deeplearning/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1150, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
  File "/opt/miniconda3/envs/deeplearning/lib/python3.10/site-packages/torch/cuda/__init__.py", line 293, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled
Exception ignored in atexit callback: <function _exit_function at 0x7fafb15a84c0>
Traceback (most recent call last):
  File "/opt/miniconda3/envs/deeplearning/lib/python3.10/multiprocessing/util.py", line 357, in _exit_function
    p.join()
  File "/opt/miniconda3/envs/deeplearning/lib/python3.10/multiprocessing/process.py", line 149, in join
    res = self._popen.wait(timeout)
  File "/opt/miniconda3/envs/deeplearning/lib/python3.10/multiprocessing/popen_fork.py", line 43, in wait
    return self.poll(os.WNOHANG if timeout == 0.0 else 0)
  File "/opt/miniconda3/envs/deeplearning/lib/python3.10/multiprocessing/popen_fork.py", line 27, in poll
    pid, sts = os.waitpid(self.pid, flag)
  File "/opt/miniconda3/envs/deeplearning/lib/python3.10/site-packages/torch/utils/data/_utils/signal_handling.py", line 66, in handler
    _error_if_any_worker_fails()
RuntimeError: DataLoader worker (pid 21232) is killed by signal: Terminated: 15. 
